version: '3.3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: project_${PROJECT_NAME}
    restart: always
    tty: true
    environment:
      SERVICE_NAME: project
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./project-LARAVEL:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: project-webserver_${PROJECT_NAME}
    restart: always
    tty: true
    ports:
      - "8888:80"
        #  - "4431:443"
    volumes:
      - ./project-LARAVEL:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network

  #MySQL Service
  db:
    platform: linux/x86_64
    image: mysql:8.0.17
    container_name: project-db_${PROJECT_NAME}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: 123456@project
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - projectdata:/var/lib/mysql
    networks:
      - laravel-network

  #adminer for db access
  adminer:
    image: adminer:latest
    restart: unless-stopped
    container_name: project-adminer_${PROJECT_NAME}
    ports:
      - 8800:8080

#Docker Networks
networks:
  laravel-network:
    driver: bridge

#Volumes
volumes:
  projectdata:
    driver: local 

